[package]
name = "itsi-server"
version = "0.1.0"
edition = "2021"
authors = ["Wouter Coppieters <wc@pico.net.nz>"]
license = "MIT"
publish = false

[lib]
crate-type = ["cdylib"]

[dependencies]
magnus = { version = "0.7.1" }
itsi_tracing = { path = "../itsi_tracing" }
itsi_rb_helpers = { path = "../itsi_rb_helpers" }
itsi_error = { path = "../itsi_error" }
parking_lot = "0.12.3"
rustls-pemfile = "2.2.0"
tokio-rustls = "0.23"
rcgen = { version = "0.13.2", features = ["x509-parser", "pem"] }
base64 = "0.22.1"
