[package]
name = "itsi_tracing"
version = "0.1.0"
edition = "2024"

[dependencies]
tracing = { version = "0.1.41", features = ["attributes"] }
tracing-subscriber = { version = "0.3.19", features = [
  "env-filter",
  "std",
  "fmt",
] }
