[package]
name = "itsi_rb_helpers"
version = "0.1.0"
edition = "2024"

[dependencies]
cfg-if = "1.0.0"
magnus = { version = "0.7.1", features = ["rb-sys", "bytes"] }
nix = "0.29.0"
rb-sys = "0.9.105"
serde = "1.0.219"
