name: Release

on:
  push:
    tags: ["v*"]

jobs:
  compile:
    strategy:
      matrix:
        include:
          - runner: ubuntu-22.04
            arch: x86_64-linux
          - runner: macos-15
            arch: arm64-darwin
    runs-on: ${{ matrix.runner }}
    steps:
      - uses: actions/checkout@v4
      - uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
          ruby-version: 3.1
      - run: bundle exec rake build precompile:${{ matrix.arch }}
      - uses: actions/upload-artifact@v4
        with:
          name: precompiled-${{ matrix.arch }}
          path: pkg/*-${{ matrix.arch }}.gem
          if-no-files-found: error
