name: Release

on:
  push:
    tags: ["v*"]

jobs:
  compile:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
          ruby-version: 3.1
      - run: bundle exec rake build precompile_linux
      - uses: actions/upload-artifact@v4
        with:
          name: precompiled-linux
          path: pkg/*-x86_64-linux.gem
