name: Test Native Ruby Gems

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    env:
      RUST_BACKTRACE: full

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.4'
          bundler-cache: true

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
          components: clippy, rustfmt

      - name: Install libclang and dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libclang-dev pkg-config

      - name: Build and Test all gems
        run: |
          bundle install
          rake test
